export const IPC = {
  browserState: "browser:state",
  focusAddressBar: "browser:focus-address-bar",
  shortcutInvoked: "browser:shortcut-invoked",
  findInPageResult: "browser:find-in-page-result",
  requestCloseConfirmation: "window:request-close-confirmation",

  getState: "browser:get-state",
  setViewInsets: "browser:set-view-insets",

  createTab: "tabs:create",
  closeTab: "tabs:close",
  duplicateTab: "tabs:duplicate",
  pinTab: "tabs:pin",
  reorderTab: "tabs:reorder",
  closeOtherTabs: "tabs:close-others",
  closeTabsToRight: "tabs:close-to-right",
  moveTabToNewWindow: "tabs:move-to-new-window",
  toggleTabMuted: "tabs:toggle-muted",
  switchTab: "tabs:switch",
  navigate: "tabs:navigate",
  goHome: "tabs:home",
  goBack: "tabs:back",
  goForward: "tabs:forward",
  reload: "tabs:reload",
  stopLoading: "tabs:stop",
  hardReload: "tabs:hard-reload",
  nextTab: "tabs:next",
  previousTab: "tabs:previous",
  reopenClosedTab: "tabs:reopen-closed",
  findInPage: "tabs:find-in-page",
  stopFindInPage: "tabs:stop-find-in-page",

  toggleBookmark: "bookmarks:toggle-current",
  removeBookmark: "bookmarks:remove",
  openBookmark: "bookmarks:open",

  clearHistory: "history:clear",
  openHistoryEntry: "history:open",

  updateSettings: "settings:update",
  clearBrowserData: "settings:clear-browser-data",
  clearNetworkCache: "settings:clear-network-cache",
  resetSettings: "settings:reset",
  getRuntimeInfo: "settings:get-runtime-info",
  openShellDevTools: "settings:open-shell-devtools",
  relaunchApp: "settings:relaunch-app",

  updateStatusChanged: "updates:status-changed",
  getUpdateStatus: "updates:get-status",
  checkForUpdates: "updates:check",
  downloadUpdate: "updates:download",
  installUpdate: "updates:install",
  openReleasesPage: "updates:open-releases-page",

  openDownload: "downloads:open",
  revealDownload: "downloads:reveal",
  chooseDownloadFolder: "downloads:choose-folder",
  openDownloadsFolder: "downloads:open-folder",
  clearDownloads: "downloads:clear",

  chooseNewTabCustomImage: "appearance:choose-new-tab-custom-image",
  removeNewTabCustomImage: "appearance:remove-new-tab-custom-image",

  clearBookmarks: "bookmarks:clear",
  importBookmarks: "bookmarks:import",
  exportBookmarks: "bookmarks:export",

  loadUnpackedExtension: "extensions:load-unpacked",
  validateUnpackedExtension: "extensions:validate-unpacked",
  ensureExtensionsWorkspace: "extensions:ensure-workspace",
  setExtensionEnabled: "extensions:set-enabled",
  removeExtension: "extensions:remove",
  reloadExtensions: "extensions:reload",
  openExtensionsFolder: "extensions:open-folder",
  listExtensionStore: "extensions:store:list",
  installStoreExtension: "extensions:store:install",
  openExtensionPanel: "extensions:panel:open",
  invokeExtensionApi: "extensions:api:invoke",
  logExtensionRuntimeMessage: "extensions:runtime:log",
  clearExtensionErrors: "extensions:errors:clear",

  passwordManagerStatusChanged: "password-manager:status-changed",
  passwordManagerGetStatus: "password-manager:get-status",
  passwordManagerSetup: "password-manager:setup",
  passwordManagerUnlock: "password-manager:unlock",
  passwordManagerUnlockWithOs: "password-manager:unlock-with-os",
  passwordManagerLock: "password-manager:lock",
  passwordManagerList: "password-manager:list",
  passwordManagerCreate: "password-manager:create",
  passwordManagerUpdate: "password-manager:update",
  passwordManagerDelete: "password-manager:delete",
  passwordManagerDuplicate: "password-manager:duplicate",
  passwordManagerGenerate: "password-manager:generate",
  passwordManagerCopyField: "password-manager:copy-field",
  passwordManagerFill: "password-manager:fill",
  passwordManagerHealth: "password-manager:health",
  passwordManagerImportCsv: "password-manager:import-csv",
  passwordManagerExportBackup: "password-manager:export-backup",
  passwordManagerImportBackup: "password-manager:import-backup",
  passwordManagerChangeMaster: "password-manager:change-master",
  passwordManagerDeleteVault: "password-manager:delete-vault",
  passwordManagerPageMessage: "password-manager:page-message",
  passwordManagerPromptAction: "password-manager:prompt-action",
  passwordManagerPromptChanged: "password-manager:prompt-changed",
  passwordManagerAutofillChanged: "password-manager:autofill-changed",

  minimizeWindow: "window:minimize",
  toggleMaximizeWindow: "window:toggle-maximize",
  closeWindow: "window:close",
  closeWindowWithBehavior: "window:close-with-behavior",
} as const;
